// <auto-generated />
using System;
using HealthyManagement.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HealthyManagement.Migrations
{
    [DbContext(typeof(HealthyManagementContext))]
    [Migration("20220504024527_TodasTabelas")]
    partial class TodasTabelas
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.16")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HealthyManagement.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CPF")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("HealthyManagement.Models.Colaborador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CPF")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Colaborador");
                });

            modelBuilder.Entity("HealthyManagement.Models.Orcamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ClienteId")
                        .HasColumnType("int");

                    b.Property<int?>("ColaboradorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataAgendado")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SituacaoOrcamento")
                        .HasColumnType("int");

                    b.Property<double>("ValorFinal")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("ColaboradorId");

                    b.ToTable("Orcamento");
                });

            modelBuilder.Entity("HealthyManagement.Models.OrcamentoServicoProduto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("OrcamentoId")
                        .HasColumnType("int");

                    b.Property<double>("Quantidade")
                        .HasColumnType("float");

                    b.Property<int?>("ServicoProdutoId")
                        .HasColumnType("int");

                    b.Property<int?>("TipoServicoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrcamentoId");

                    b.HasIndex("ServicoProdutoId");

                    b.HasIndex("TipoServicoId");

                    b.ToTable("OrcamentoServicoProduto");
                });

            modelBuilder.Entity("HealthyManagement.Models.ServicoProduto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Preco")
                        .HasColumnType("float");

                    b.Property<int>("TipoVenda")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ServicoProduto");
                });

            modelBuilder.Entity("HealthyManagement.Models.TipoServico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Percentual")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("TipoServico");
                });

            modelBuilder.Entity("HealthyManagement.Models.Orcamento", b =>
                {
                    b.HasOne("HealthyManagement.Models.Cliente", "Cliente")
                        .WithMany("Orcamentos")
                        .HasForeignKey("ClienteId");

                    b.HasOne("HealthyManagement.Models.Colaborador", "Colaborador")
                        .WithMany("Orcamentos")
                        .HasForeignKey("ColaboradorId");

                    b.Navigation("Cliente");

                    b.Navigation("Colaborador");
                });

            modelBuilder.Entity("HealthyManagement.Models.OrcamentoServicoProduto", b =>
                {
                    b.HasOne("HealthyManagement.Models.Orcamento", "Orcamento")
                        .WithMany("OrcamentosServicosProdutos")
                        .HasForeignKey("OrcamentoId");

                    b.HasOne("HealthyManagement.Models.ServicoProduto", "ServicoProduto")
                        .WithMany("OrcamentosServicosProdutos")
                        .HasForeignKey("ServicoProdutoId");

                    b.HasOne("HealthyManagement.Models.TipoServico", "TipoServico")
                        .WithMany("OrcamentosServicosProdutos")
                        .HasForeignKey("TipoServicoId");

                    b.Navigation("Orcamento");

                    b.Navigation("ServicoProduto");

                    b.Navigation("TipoServico");
                });

            modelBuilder.Entity("HealthyManagement.Models.Cliente", b =>
                {
                    b.Navigation("Orcamentos");
                });

            modelBuilder.Entity("HealthyManagement.Models.Colaborador", b =>
                {
                    b.Navigation("Orcamentos");
                });

            modelBuilder.Entity("HealthyManagement.Models.Orcamento", b =>
                {
                    b.Navigation("OrcamentosServicosProdutos");
                });

            modelBuilder.Entity("HealthyManagement.Models.ServicoProduto", b =>
                {
                    b.Navigation("OrcamentosServicosProdutos");
                });

            modelBuilder.Entity("HealthyManagement.Models.TipoServico", b =>
                {
                    b.Navigation("OrcamentosServicosProdutos");
                });
#pragma warning restore 612, 618
        }
    }
}
